#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ae
Version  : 1.8.2
Release  : 3
URL      : https://rubygems.org/downloads/ae-1.8.2.gem
Source0  : https://rubygems.org/downloads/ae-1.8.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
BuildRequires : ruby
BuildRequires : rubygem-ansi
BuildRequires : rubygem-detroit
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
# Assertive Expressive
[Homepage](http://rubyworks.github.com/ae) /
[Source Code](http://github.com/rubyworks/ae) /
[Documentation](http://rubydoc.info/gems/ae) /
[User Manual](http://wiki.github.com/rubyworks/ae) /
[Report Issue](http://github.com/rubyworks/ae/issues) /
[Mailing List](http://googlegroups.com/group/rubyworks-mailinglist) /
[IRC Channel](irc://irc.freenode.net/rubyworks) &nbsp; &nbsp;
[![Build Status](https://secure.travis-ci.org/rubyworks/qed.png)](http://travis-ci.org/rubyworks/ae)
[![Gem Version](https://badge.fury.io/rb/qed.png)](http://badge.fury.io/rb/ae)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ae-1.8.2
gem spec %{SOURCE0} -l --ruby > rubygem-ae.gemspec

%build
gem build rubygem-ae.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ae-1.8.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ae-1.8.2.gem
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assert/assert%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assert/assert%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assert/assert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assert/cdesc-Assert.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assert/flunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assert/refute%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assert/refute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertion/assertion%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertion/cdesc-Assertion.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertion/counts-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertion/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertion/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/%3d%7e-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/__assert__-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/assay_assertion%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/assay_assertion_apply-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/assert-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/assert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/assertion_error-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/cdesc-Assertor.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/compare_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/counts-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/exception%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/expect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/flunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/generic_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/increment_counts-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/not-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/proc_apply-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/proc_assertion%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/raise_assertion-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/recount-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/rspec_matcher%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/rspec_matcher_apply-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/rspec_matcher_message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Assertor/send-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/BasicObject/cdesc-BasicObject.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/call-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/cdesc-Proc.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/message%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/message-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/no%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/ok%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/Proc/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/__check__-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/cdesc-Check.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/check-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/check_table-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/define-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/no-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/ok-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Check/table-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Expect/cdesc-Expect.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Expect/expect%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Expect/expect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Expect/expected-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Expect/forbid-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/__assert__-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_in_delta-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_includes-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_instance_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_kind_of-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_nil-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_no_match-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_not_equal-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_not_nil-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_not_same-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_operator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_raise-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_raises-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_respond_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_same-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_send-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/assert_throws-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/cdesc-Assertions.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/Assertions/flunk-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Legacy/cdesc-Legacy.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Must/cdesc-Must.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Must/must%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Must/must%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Must/must-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Must/must_not-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Must/mustnt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Must/wont-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Should/cdesc-Should.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Should/should%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Should/should%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Should/should-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Should/should_not-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Should/shouldnt-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Subjunctive/a-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Subjunctive/an-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Subjunctive/be-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Subjunctive/cdesc-Subjunctive.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Subjunctive/does-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/Subjunctive/is-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/World/cdesc-World.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/ansi%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/ansi%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/assertion_error%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/cdesc-AE.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/const_missing-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/AE/metadata-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Exception/assertion%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Exception/cdesc-Exception.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Exception/negative%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Exception/raised%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Exception/set_assertion-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Exception/set_negative-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/Pry/cdesc-Pry.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/Pry/method_missing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/Pry/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/basic_object_method_added-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/case%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/eq%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/equate%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/false%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/identical%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/identical_to%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/match%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/method_added-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/pry-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/public_send-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/send%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Kernel/true%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/MiniTest/Unit/cdesc-Unit.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/MiniTest/cdesc-MiniTest.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Module/cdesc-Module.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Module/is%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Numeric/cdesc-Numeric.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Numeric/close%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Numeric/in_delta%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Numeric/in_epsilon%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Object/basic_object_method_added-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Object/eql%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Object/equal%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Object/find_hidden_method-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Object/method_added-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Proc/cdesc-Proc.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Proc/change%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Proc/raises%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Proc/throws%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/RSpec/Expectations/cdesc-Expectations.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/RSpec/cdesc-RSpec.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Symbol/thrown%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Test/Unit/TestCase/cdesc-TestCase.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Test/Unit/cdesc-Unit.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/Test/cdesc-Test.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/page-DEMO_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/page-HISTORY_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/page-NOTICE_md.ri
/usr/lib64/ruby/gems/2.2.0/doc/ae-1.8.2/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/.ruby
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/.yardopts
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/DEMO.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/HISTORY.md
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/NOTICE.md
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae.yml
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/adapters/minitest.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/adapters/rspec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/adapters/testunit.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/ansi.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/assert.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/assertion.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/assertor.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/basic_object.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/check.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/core_ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/core_ext/exception.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/core_ext/helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/expect.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/legacy.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/must.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/pry.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/should.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/subjunctive.rb
/usr/lib64/ruby/gems/2.2.0/gems/ae-1.8.2/lib/ae/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/ae-1.8.2.gemspec
