#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ae
Version  : 1.8.2
Release  : 6
URL      : https://rubygems.org/downloads/ae-1.8.2.gem
Source0  : https://rubygems.org/downloads/ae-1.8.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
BuildRequires : ruby
BuildRequires : rubygem-ansi
BuildRequires : rubygem-detroit
BuildRequires : rubygem-qed
BuildRequires : rubygem-rdoc

%description
# Assertive Expressive
[Homepage](http://rubyworks.github.com/ae) /
[Source Code](http://github.com/rubyworks/ae) /
[Documentation](http://rubydoc.info/gems/ae) /
[User Manual](http://wiki.github.com/rubyworks/ae) /
[Report Issue](http://github.com/rubyworks/ae/issues) /
[Mailing List](http://googlegroups.com/group/rubyworks-mailinglist) /
[IRC Channel](irc://irc.freenode.net/rubyworks) &nbsp; &nbsp;
[![Build Status](https://secure.travis-ci.org/rubyworks/qed.png)](http://travis-ci.org/rubyworks/ae)
[![Gem Version](https://badge.fury.io/rb/qed.png)](http://badge.fury.io/rb/ae)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ae-1.8.2
gem spec %{SOURCE0} -l --ruby > rubygem-ae.gemspec

%build
gem build rubygem-ae.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ae-1.8.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ae-1.8.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/.ruby
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/DEMO.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/NOTICE.md
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae.yml
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/adapters/minitest.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/adapters/rspec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/adapters/testunit.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/ansi.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/assert.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/assertion.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/assertor.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/basic_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/check.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/core_ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/core_ext/exception.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/core_ext/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/expect.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/legacy.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/must.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/pry.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/should.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/subjunctive.rb
/usr/lib64/ruby/gems/2.3.0/gems/ae-1.8.2/lib/ae/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ae-1.8.2.gemspec
